/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import java.sql.*;
import javax.swing.JOptionPane;
import main.helper.DBConnection;

/**
 *
 * @author Baler-Gamer
 */
public class LoginScreen extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    ResultSet res;
    
    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginEmail = new javax.swing.JTextField();
        loginPass = new javax.swing.JPasswordField();
        cancelLogin = new javax.swing.JButton();
        registerBtn = new javax.swing.JLabel();
        resetPass = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tHomeBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("تسجيل الدخول ");
        setMaximumSize(new java.awt.Dimension(828, 519));
        setMinimumSize(new java.awt.Dimension(828, 519));
        setPreferredSize(new java.awt.Dimension(828, 519));
        setResizable(false);
        setSize(new java.awt.Dimension(828, 519));

        loginEmail.setBackground(new java.awt.Color(204, 204, 204));
        loginEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 25));

        loginPass.setBackground(new java.awt.Color(204, 204, 204));
        loginPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 25));
        loginPass.setPreferredSize(new java.awt.Dimension(51, 22));

        cancelLogin.setBackground(new java.awt.Color(255, 153, 0));
        cancelLogin.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cancelLogin.setText("إلغاء\n");
        cancelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelLoginMouseClicked(evt);
            }
        });

        registerBtn.setBackground(new java.awt.Color(0, 102, 255));
        registerBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(102, 102, 102));
        registerBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        registerBtn.setText("ليس لديك حساب؟ سجل الان\n");
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBtnMouseClicked(evt);
            }
        });

        resetPass.setBackground(new java.awt.Color(0, 102, 255));
        resetPass.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        resetPass.setForeground(new java.awt.Color(0, 0, 204));
        resetPass.setText("هل نسيت كلمة المرور\n");
        resetPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetPassMouseClicked(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(0, 153, 153));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(240, 240, 240));
        loginBtn.setText("تسجيل الدخول");
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("كلمة المرور ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("رقم الهوية الوطنية ");

        tHomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_home_40px.png"))); // NOI18N
        tHomeBtn.setToolTipText("Go Home");
        tHomeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tHomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tHomeBtnMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tHomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginPass, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(cancelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(resetPass, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(loginEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tHomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)
                        .addComponent(loginEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(loginPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(resetPass)
                .addGap(25, 25, 25)
                .addComponent(registerBtn)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelLoginMouseClicked
        this.dispose();
        new StartScreen().setVisible(true);
    }//GEN-LAST:event_cancelLoginMouseClicked

    private void registerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseClicked
        this.dispose();
        new RegisterScreen().setVisible(true);
    }//GEN-LAST:event_registerBtnMouseClicked

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked

        String userName = loginEmail.getText();
        String password = loginPass.getText();
        
        if(userName.equals("") || password.equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "اسم المستخدم أو كلمة المرور فارغة");
        }
        else
        {
            try {
            con = DBConnection.getConnection();
            pst = con.prepareStatement("select * from user where (email='"+userName+"' or student_id='"+userName+"'"
                    + " or phone='"+userName+"') and password='"+password+"'");
            res = pst.executeQuery();
            
            if(res.next())
            {
               String name = res.getString("fullname");
               int id = res.getInt("ID");
               String cv = res.getString("cv");
               this.dispose();
               new MainScreen(name,id,cv).setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "اسم المستخدم أو كلمة المرور غير صحيحة");
            }
            
            
            
            
            } catch (Exception e) {
                System.out.println(e);
            }
        }
        
    }//GEN-LAST:event_loginBtnMouseClicked

    private void resetPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPassMouseClicked
        new ResetPassScreen().setVisible(true);
    }//GEN-LAST:event_resetPassMouseClicked

    private void tHomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tHomeBtnMouseClicked
        this.dispose();
        new FirstScreen().setVisible(true);
    }//GEN-LAST:event_tHomeBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField loginEmail;
    private javax.swing.JPasswordField loginPass;
    private javax.swing.JLabel registerBtn;
    private javax.swing.JLabel resetPass;
    private javax.swing.JLabel tHomeBtn;
    // End of variables declaration//GEN-END:variables
}
