/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static main.MainScreen.f;
import static main.MainScreen.file;
import main.helper.DBConnection;
import main.helper.FileURL;
/**
 *
 * @author Baler-Gamer
 */
public class RegisterScreen extends javax.swing.JFrame {
    public static JFileChooser file = new JFileChooser();
    public static File f;
    public static Connection con;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form RegisterScreen
     */
    public RegisterScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email = new javax.swing.JTextField();
        nationality = new javax.swing.JTextField();
        ac_qualification = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        fullname = new javax.swing.JTextField();
        cancelRegistration = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        specialization = new javax.swing.JTextField();
        pass1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cvChoose = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        fileName = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        tHomeBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("تسجيل ");
        setMaximumSize(new java.awt.Dimension(828, 525));
        setMinimumSize(new java.awt.Dimension(828, 525));
        setPreferredSize(new java.awt.Dimension(828, 525));
        setSize(new java.awt.Dimension(828, 525));
        getContentPane().setLayout(null);

        email.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(email);
        email.setBounds(80, 220, 170, 30);

        nationality.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(nationality);
        nationality.setBounds(270, 220, 170, 30);

        ac_qualification.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(ac_qualification);
        ac_qualification.setBounds(80, 130, 170, 30);

        phone.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(phone);
        phone.setBounds(470, 130, 170, 30);

        pass.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(pass);
        pass.setBounds(80, 310, 170, 30);

        fullname.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(fullname);
        fullname.setBounds(80, 60, 170, 30);

        cancelRegistration.setBackground(new java.awt.Color(255, 102, 51));
        cancelRegistration.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cancelRegistration.setForeground(new java.awt.Color(240, 240, 240));
        cancelRegistration.setText("إلغاء ");
        cancelRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelRegistrationMouseClicked(evt);
            }
        });
        getContentPane().add(cancelRegistration);
        cancelRegistration.setBounds(190, 370, 90, 30);

        registerBtn.setBackground(new java.awt.Color(0, 204, 153));
        registerBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(240, 240, 240));
        registerBtn.setText("موافق ");
        registerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBtnMouseClicked(evt);
            }
        });
        getContentPane().add(registerBtn);
        registerBtn.setBounds(80, 370, 90, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("الأسم بالكامل ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 30, 170, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("البريد الألكتروني ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 190, 170, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("رقم الجوال ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(470, 100, 170, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("الجنسية ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 190, 170, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("كلمة المرور ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 280, 170, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("المؤهل ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 100, 170, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(710, 0, 100, 100);

        id.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(id);
        id.setBounds(270, 60, 170, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("رقم الهوية الوطنية ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 30, 170, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("الجنس ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(470, 30, 170, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("التخصص ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(270, 100, 170, 20);

        specialization.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(specialization);
        specialization.setBounds(270, 130, 170, 30);

        pass1.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(pass1);
        pass1.setBounds(270, 310, 170, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("إعادة كتابة كلمة المرور ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(270, 280, 170, 20);

        cvChoose.setText("التصفح ");
        cvChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvChooseActionPerformed(evt);
            }
        });
        getContentPane().add(cvChoose);
        cvChoose.setBounds(600, 310, 73, 23);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 0));
        jLabel12.setText("تحميل السيرة الذاتية ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(460, 310, 140, 20);
        getContentPane().add(fileName);
        fileName.setBounds(600, 340, 230, 20);

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ذكر", "أنثى", "أخرى" }));
        getContentPane().add(gender);
        gender.setBounds(470, 60, 170, 30);

        tHomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_home_40px.png"))); // NOI18N
        tHomeBtn.setToolTipText("Go Home");
        tHomeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tHomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tHomeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(tHomeBtn);
        tHomeBtn.setBounds(10, 10, 50, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelRegistrationMouseClicked
        this.dispose();
        new StartScreen().setVisible(true);
    }//GEN-LAST:event_cancelRegistrationMouseClicked

    private void registerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseClicked
        String name = fullname.getText();
        String userEmail = email.getText();
        String userPhone = phone.getText();
        String academic = ac_qualification.getText();
        String nation = nationality.getText();
        String password = pass.getText();
        String specialize = specialization.getText();
        String myID = id.getText();
        String myGender = gender.getSelectedItem().toString();
        
        
        if(name.equals("") || userEmail.equals("") || userPhone.equals("") || academic.equals("") ||
                nation.equals("") || password.equals("") || specialize.equals("") || myID.equals("") ||
                myGender.equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "يرجى ملء كل النص بشكل صحيح");
        }
        else if(f == null)
        {
           JOptionPane.showMessageDialog(rootPane, "الرجاء تحميل السيرة الذاتية");
        }
        else if(!password.equals(pass1.getText()))
        {
            JOptionPane.showMessageDialog(rootPane, "كلمة المرور خاطئة");
        }
        else
        {
            int userCheck = userExist(myID, userPhone, userEmail);
            if(userCheck == SUCCESS)
            {
                int max = 99999999;
                int min = 1;

                int random_int_1 = (int)(Math.random() * (max - min + 1) + min);
                int randomg_int_2 = (int)(Math.random() * (50 - 100 + 1) + 50);
                String pathFrom = "";
                String new_file_name ="";
                String pathTo = "";

                if(f != null)
                {
                    pathFrom = f.getAbsolutePath();
                    new_file_name = random_int_1+"_"+randomg_int_2+"_"+"user"+f.getName().substring(f.getName().lastIndexOf("."),
                            f.getName().length());
                    pathTo = FileURL.uploadFolder+"/"+new_file_name;
                    Path source = Paths.get(pathFrom);
                    Path target = Paths.get(pathTo);
                    try {
                        Files.copy(source,target);
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                }
                try {
                    con = DBConnection.getConnection();
                    pst = con.prepareStatement("insert into user (student_id,fullname,email,phone,qualification,"
                            + "specialization,password,gender,nationality,cv)"
                            + " values(?,?,?,?,?,?,?,?,?,?)");
                    pst.setString(1,myID);
                    pst.setString(2,name);
                    pst.setString(3,userEmail);
                    pst.setString(4,userPhone);
                    pst.setString(5,academic);
                    pst.setString(6,specialize);
                    pst.setString(7,password);
                    pst.setString(8,myGender);
                    pst.setString(9,nation);
                    pst.setString(10,new_file_name);
                    pst.executeUpdate();


                    int ok = JOptionPane.showConfirmDialog(rootPane, "الذهاب إلى صفحة تسجيل الدخول وتسجيل الدخول مرة أخرى؟",
                            "تم بنجاح التسجيل",JOptionPane.OK_OPTION);
                    if(ok == 0)
                    {
                        this.dispose();
                        new StartScreen().setVisible(true);
                    }
                    else
                    {
                        this.dispose();
                        new StartScreen().setVisible(true);
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
            else if(userCheck == INVALID_ID)
            {
                JOptionPane.showMessageDialog(rootPane, "يوجد بالفعل مستخدم بنفس رقم الهوية","Failed",JOptionPane.ERROR_MESSAGE);
            }
            else if(userCheck == INVALID_PHONE)
            {
                JOptionPane.showMessageDialog(rootPane, "يوجد بالفعل مستخدم بنفس رقم الجوال","Failed",JOptionPane.ERROR_MESSAGE);
            }
            else if(userCheck == INVALID_EMAIL)
            {
                JOptionPane.showMessageDialog(rootPane, "يوجد بالفعل مستخدم بنفس الايميل ","Failed",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_registerBtnMouseClicked

    private void cvChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvChooseActionPerformed
        int returnVal = file.showOpenDialog(jLabel5);
        if(returnVal == JFileChooser.APPROVE_OPTION){
            f = file.getSelectedFile();
            String name = f.getName();
            fileName.setText(name);
        }
    }//GEN-LAST:event_cvChooseActionPerformed

    private void tHomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tHomeBtnMouseClicked
        this.dispose();
        new FirstScreen().setVisible(true);
    }//GEN-LAST:event_tHomeBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterScreen().setVisible(true);
            }
        });
    }
//    Check If user exist or not
    private static final int SUCCESS = 0;
    private static final int INVALID_ID = 1;
    private static final int INVALID_EMAIL = 2;
    private static final int INVALID_PHONE = 3;
    
    public static int userExist(String ID,String phone, String email)
    {
        int status = 0;
        con = DBConnection.getConnection();
        try {
            PreparedStatement checkID = con.prepareStatement("select student_id from user where student_id='"+ID+"'");
            PreparedStatement checkPhone = con.prepareStatement("select student_id from user where phone='"+phone+"'");
            PreparedStatement checkEmail = con.prepareStatement("select student_id from user where email='"+email+"'");
            ResultSet rs1 = checkID.executeQuery();
            ResultSet rs2 = checkPhone.executeQuery();
            ResultSet rs3 = checkEmail.executeQuery();
            if(rs1.next())
            {
                status = INVALID_ID;
            }
            else if(rs2.next())
            {
                status = INVALID_PHONE;
            }
            else if(rs3.next())
            {
                status = INVALID_EMAIL;
            }
            else
            {
                status = SUCCESS;
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(RegisterScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        return status;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ac_qualification;
    private javax.swing.JButton cancelRegistration;
    private javax.swing.JButton cvChoose;
    private javax.swing.JTextField email;
    private javax.swing.JLabel fileName;
    private javax.swing.JTextField fullname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nationality;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField pass1;
    private javax.swing.JTextField phone;
    private javax.swing.JButton registerBtn;
    private javax.swing.JTextField specialization;
    private javax.swing.JLabel tHomeBtn;
    // End of variables declaration//GEN-END:variables
}
