/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.*;
import java.text.DateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import main.helper.DBConnection;
import main.helper.FileURL;

/**
 *
 * @author Baler-Gamer
 */
public class TrainingMainScreen extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    ResultSet res;
    
    public static int userID;
    public static String insName;
    public static String sector;

    /**
     * Creates new form MainScreen
     * @param userName
     * @param id
     */
    public TrainingMainScreen(String userName, int id, String sec) {
        initComponents();
        this.setLocationRelativeTo(null);
        userNameText.setText(userName);
        userID = id;
        insName = userName;
        sector = sec;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tName = new javax.swing.JTextField();
        logoutBtn = new javax.swing.JLabel();
        infoBtn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userNameText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        startDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        tTime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        submitTraining = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("الصفحة الرئيسية ");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        tName.setBackground(new java.awt.Color(204, 204, 204));
        tName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        jPanel1.add(tName);
        tName.setBounds(120, 160, 380, 40);

        logoutBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logout.png"))); // NOI18N
        logoutBtn.setText("تسجيل خروج ");
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });
        jPanel1.add(logoutBtn);
        logoutBtn.setBounds(20, 20, 110, 30);

        infoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/info.png"))); // NOI18N
        infoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoBtnMouseClicked(evt);
            }
        });
        jPanel1.add(infoBtn);
        infoBtn.setBounds(160, 20, 24, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("أهلا بك ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(680, 20, 90, 30);

        userNameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userNameText.setForeground(new java.awt.Color(0, 153, 204));
        userNameText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userNameText.setText("Easin Sazzad");
        jPanel1.add(userNameText);
        userNameText.setBounds(370, 20, 330, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("تاريخ بدء التدريب ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(530, 240, 160, 40);

        startDate.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(startDate);
        startDate.setBounds(120, 240, 380, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("اسم جهة التدريب ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(530, 160, 160, 40);

        tTime.setBackground(new java.awt.Color(204, 204, 204));
        tTime.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        jPanel1.add(tTime);
        tTime.setBounds(120, 320, 380, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("وقت التدريب ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(530, 320, 130, 40);

        submitTraining.setText("إرسال ");
        submitTraining.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitTrainingMouseClicked(evt);
            }
        });
        jPanel1.add(submitTraining);
        submitTraining.setBounds(120, 400, 100, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        this.dispose();
        new StartScreen().setVisible(true);
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void infoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseClicked
        new AboutScreen().setVisible(true);
    }//GEN-LAST:event_infoBtnMouseClicked

    private void submitTrainingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitTrainingMouseClicked
        String trainingName = tName.getText();
        String tDate = ((JTextField)startDate.getDateEditor().getUiComponent()).getText();
        String trTime = tTime.getText();
        if(trainingName.equals("") || tDate.equals("") || trTime.equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "الرجاء تعبئة الخانات الفارغة","Info",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try{
                con = DBConnection.getConnection();
                pst = con.prepareStatement("insert into trainings (ins_id,ins_name,training_name,training_start_date,"
                        + "training_time,sector) values(?,?,?,?,?,?)");
                pst.setInt(1,userID);
                pst.setString(2,insName);
                pst.setString(3,trainingName);
                pst.setString(4,tDate);
                pst.setString(5,trTime);
                pst.setString(6,sector);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "تم إدخال بيانات التدريب");
                con.close();
                tTime.setText("");
                tName.setText("");
                
                
            }
            catch(HeadlessException | SQLException e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_submitTrainingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainingMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainingMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainingMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainingMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel infoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoutBtn;
    private com.toedter.calendar.JDateChooser startDate;
    private javax.swing.JButton submitTraining;
    private javax.swing.JTextField tName;
    private javax.swing.JTextField tTime;
    private javax.swing.JLabel userNameText;
    // End of variables declaration//GEN-END:variables
}
