/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import java.sql.*;
import javax.swing.JOptionPane;
import main.helper.DBConnection;

/**
 *
 * @author Baler-Gamer
 */
public class TrainingLoginScreen extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    ResultSet res;
    
    /**
     * Creates new form LoginScreen
     */
    public TrainingLoginScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginEmail = new javax.swing.JTextField();
        loginPass = new javax.swing.JPasswordField();
        cancelLogin = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tregBtn = new javax.swing.JLabel();
        tChangePass = new javax.swing.JLabel();
        tHomeBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("تسجيل الدخول ");
        setMinimumSize(new java.awt.Dimension(828, 519));
        setResizable(false);
        setSize(new java.awt.Dimension(828, 519));
        getContentPane().setLayout(null);

        loginEmail.setBackground(new java.awt.Color(204, 204, 204));
        loginEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 25));
        getContentPane().add(loginEmail);
        loginEmail.setBounds(210, 50, 340, 40);

        loginPass.setBackground(new java.awt.Color(204, 204, 204));
        loginPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 25));
        loginPass.setPreferredSize(new java.awt.Dimension(51, 22));
        getContentPane().add(loginPass);
        loginPass.setBounds(210, 150, 340, 40);

        cancelLogin.setBackground(new java.awt.Color(255, 153, 0));
        cancelLogin.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cancelLogin.setText("إلغاء ");
        cancelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelLoginMouseClicked(evt);
            }
        });
        getContentPane().add(cancelLogin);
        cancelLogin.setBounds(440, 210, 110, 40);

        loginBtn.setBackground(new java.awt.Color(0, 153, 153));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(240, 240, 240));
        loginBtn.setText("تسجيل الدخول ");
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
        });
        getContentPane().add(loginBtn);
        loginBtn.setBounds(310, 210, 110, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("الرمز ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 110, 70, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("رقم ID الجهة التدريبيه ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 20, 160, 22);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(710, 0, 100, 100);

        tregBtn.setForeground(new java.awt.Color(102, 102, 102));
        tregBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tregBtn.setText("ليس لديك حساب ؟ سجل الان  ");
        tregBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tregBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tregBtnMouseClicked(evt);
            }
        });
        getContentPane().add(tregBtn);
        tregBtn.setBounds(350, 320, 200, 14);

        tChangePass.setForeground(new java.awt.Color(0, 204, 204));
        tChangePass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tChangePass.setText("هل نسيت كلمة المرور؟ ");
        tChangePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tChangePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tChangePassMouseClicked(evt);
            }
        });
        getContentPane().add(tChangePass);
        tChangePass.setBounds(420, 270, 130, 14);

        tHomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_home_40px.png"))); // NOI18N
        tHomeBtn.setToolTipText("Go Home");
        tHomeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tHomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tHomeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(tHomeBtn);
        tHomeBtn.setBounds(10, 10, 50, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelLoginMouseClicked
        this.dispose();
        new TrainingStartScreen().setVisible(true);
    }//GEN-LAST:event_cancelLoginMouseClicked

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked

        String userName = loginEmail.getText();
        String password = loginPass.getText();
        
        if(userName.equals("") || password.equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "اسم المستخدم أو كلمة المرور فارغة");
        }
        else
        {
            try {
            con = DBConnection.getConnection();
            pst = con.prepareStatement("select * from training_inst where (ins_id=? or email=?) and password=?");
            pst.setString(1,userName);
            pst.setString(2,userName);
            pst.setString(3,password);
            res = pst.executeQuery();
            
            if(res.next())
            {
               String name = res.getString("ins_name");
               int id = res.getInt("ID");
               String sec = res.getString("sector");
               this.dispose();
               new TrainingMainScreen(name,id,sec).setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "فشل تسجيل الدخول");
            }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
        
    }//GEN-LAST:event_loginBtnMouseClicked

    private void tChangePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tChangePassMouseClicked
        new TrainingResetPass().setVisible(true);
    }//GEN-LAST:event_tChangePassMouseClicked

    private void tregBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tregBtnMouseClicked
        this.dispose();
        new TrainingRegisterScreen().setVisible(true);
    }//GEN-LAST:event_tregBtnMouseClicked

    private void tHomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tHomeBtnMouseClicked
        this.dispose();
        new FirstScreen().setVisible(true);
    }//GEN-LAST:event_tHomeBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainingLoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainingLoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainingLoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainingLoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainingLoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField loginEmail;
    private javax.swing.JPasswordField loginPass;
    private javax.swing.JLabel tChangePass;
    private javax.swing.JLabel tHomeBtn;
    private javax.swing.JLabel tregBtn;
    // End of variables declaration//GEN-END:variables
}
